#pragma checksum "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "8415188FCAACD85D3444C98D541050E1F9E8D3329AEE50313D428F34B30DB5AA"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using rtwin.View.master.shift;


namespace rtwin.View.master.shift {
    
    
    /// <summary>
    /// FormShiftMingguan
    /// </summary>
    public partial class FormShiftMingguan : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 46 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtKodeShift;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtnamaGrup;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbSatker;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.ToggleButton chkLiburNasional;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbMinggu_;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbSenin;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbSelasa;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbRabu;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbKamis;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbJumat;
        
        #line default
        #line hidden
        
        
        #line 125 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbSabtu;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnsave;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClose;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel lodongSave;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/rtwin;component/view/master/shift/formshiftmingguan.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.txtKodeShift = ((System.Windows.Controls.TextBox)(target));
            return;
            case 2:
            this.txtnamaGrup = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.cmbSatker = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 4:
            this.chkLiburNasional = ((System.Windows.Controls.Primitives.ToggleButton)(target));
            return;
            case 5:
            this.cmbMinggu_ = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 6:
            this.cmbSenin = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.cmbSelasa = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 8:
            this.cmbRabu = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 9:
            this.cmbKamis = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 10:
            this.cmbJumat = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 11:
            this.cmbSabtu = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 12:
            this.btnsave = ((System.Windows.Controls.Button)(target));
            
            #line 129 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
            this.btnsave.Click += new System.Windows.RoutedEventHandler(this.Btnsave_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.btnClose = ((System.Windows.Controls.Button)(target));
            
            #line 132 "..\..\..\..\..\View\master\shift\FormShiftMingguan.xaml"
            this.btnClose.Click += new System.Windows.RoutedEventHandler(this.BtnClose_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.lodongSave = ((System.Windows.Controls.StackPanel)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

