#pragma checksum "..\..\..\..\..\View\transaksi\manual\manual.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "CD1A9FFA241CFE89A9DA7265391771166C7E5647BC25A5C12307761E04DE31D1"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignExtensions.Controls;
using MaterialDesignExtensions.Converters;
using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using rtwin.View.transaksi.manual;
using rtwin.ViewModel;


namespace rtwin.View.transaksi.manual {
    
    
    /// <summary>
    /// manual
    /// </summary>
    public partial class manual : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 29 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddData;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSearch;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.DialogHost dialog;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker dpTglAwal;
        
        #line default
        #line hidden
        
        
        #line 46 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker dpTglAkhir;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtNip;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbKodeDeputi;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbKodeBiro;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnTampilkan;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbSort;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSort;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon arrowSort;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dgManual;
        
        #line default
        #line hidden
        
        
        #line 125 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button firstPage;
        
        #line default
        #line hidden
        
        
        #line 128 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button prevPage;
        
        #line default
        #line hidden
        
        
        #line 134 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock dari;
        
        #line default
        #line hidden
        
        
        #line 137 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock sampai;
        
        #line default
        #line hidden
        
        
        #line 140 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock total;
        
        #line default
        #line hidden
        
        
        #line 145 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button nextPage;
        
        #line default
        #line hidden
        
        
        #line 148 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button lastPage;
        
        #line default
        #line hidden
        
        
        #line 155 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbJumData;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/rtwin;component/view/transaksi/manual/manual.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btnAddData = ((System.Windows.Controls.Button)(target));
            
            #line 29 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
            this.btnAddData.Click += new System.Windows.RoutedEventHandler(this.BtnAddData_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnSearch = ((System.Windows.Controls.Button)(target));
            
            #line 30 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
            this.btnSearch.Click += new System.Windows.RoutedEventHandler(this.BtnSearch_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.dialog = ((MaterialDesignThemes.Wpf.DialogHost)(target));
            return;
            case 4:
            this.dpTglAwal = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 5:
            this.dpTglAkhir = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 6:
            this.txtNip = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.cmbKodeDeputi = ((System.Windows.Controls.ComboBox)(target));
            
            #line 57 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
            this.cmbKodeDeputi.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbKodeDeputi_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.cmbKodeBiro = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 9:
            this.btnTampilkan = ((System.Windows.Controls.Button)(target));
            
            #line 67 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
            this.btnTampilkan.Click += new System.Windows.RoutedEventHandler(this.BtnTampilkan_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.cmbSort = ((System.Windows.Controls.ComboBox)(target));
            
            #line 80 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
            this.cmbSort.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbSort_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 11:
            this.btnSort = ((System.Windows.Controls.Button)(target));
            
            #line 84 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
            this.btnSort.Click += new System.Windows.RoutedEventHandler(this.BtnSort_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.arrowSort = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 13:
            this.dgManual = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 16:
            this.firstPage = ((System.Windows.Controls.Button)(target));
            
            #line 125 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
            this.firstPage.Click += new System.Windows.RoutedEventHandler(this.FirstPage_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.prevPage = ((System.Windows.Controls.Button)(target));
            
            #line 128 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
            this.prevPage.Click += new System.Windows.RoutedEventHandler(this.PrevPage_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.dari = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.sampai = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 20:
            this.total = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 21:
            this.nextPage = ((System.Windows.Controls.Button)(target));
            
            #line 145 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
            this.nextPage.Click += new System.Windows.RoutedEventHandler(this.NextPage_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.lastPage = ((System.Windows.Controls.Button)(target));
            
            #line 148 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
            this.lastPage.Click += new System.Windows.RoutedEventHandler(this.LastPage_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.cmbJumData = ((System.Windows.Controls.ComboBox)(target));
            
            #line 155 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
            this.cmbJumData.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbJumData_SelectionChanged);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 14:
            
            #line 96 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Edit_Click);
            
            #line default
            #line hidden
            break;
            case 15:
            
            #line 107 "..\..\..\..\..\View\transaksi\manual\manual.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Hapus_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

