#pragma checksum "..\..\..\..\..\View\master\shift\shftMingguan.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "D25DC1E619383F014583686213D86A75786C39C90BE09CB4444F95821C0D962E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using rtwin.View.master.shift;


namespace rtwin.View.master.shift {
    
    
    /// <summary>
    /// shftMingguan
    /// </summary>
    public partial class shftMingguan : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 29 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddData;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbSort;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSort;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon arrowSort;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dgShiftMingguan;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn edit_header;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn hapus_header;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button firstPage;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button prevPage;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock dari;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock sampai;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock total;
        
        #line default
        #line hidden
        
        
        #line 104 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button nextPage;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button lastPage;
        
        #line default
        #line hidden
        
        
        #line 114 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbJumData;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/rtwin;component/view/master/shift/shftmingguan.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btnAddData = ((System.Windows.Controls.Button)(target));
            
            #line 29 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
            this.btnAddData.Click += new System.Windows.RoutedEventHandler(this.BtnAddData_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.cmbSort = ((System.Windows.Controls.ComboBox)(target));
            
            #line 38 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
            this.cmbSort.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbSort_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btnSort = ((System.Windows.Controls.Button)(target));
            
            #line 42 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
            this.btnSort.Click += new System.Windows.RoutedEventHandler(this.BtnSort_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.arrowSort = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 5:
            this.dgShiftMingguan = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 6:
            this.edit_header = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 8:
            this.hapus_header = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 10:
            this.firstPage = ((System.Windows.Controls.Button)(target));
            
            #line 84 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
            this.firstPage.Click += new System.Windows.RoutedEventHandler(this.FirstPage_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.prevPage = ((System.Windows.Controls.Button)(target));
            
            #line 87 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
            this.prevPage.Click += new System.Windows.RoutedEventHandler(this.PrevPage_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.dari = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.sampai = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.total = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.nextPage = ((System.Windows.Controls.Button)(target));
            
            #line 104 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
            this.nextPage.Click += new System.Windows.RoutedEventHandler(this.NextPage_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.lastPage = ((System.Windows.Controls.Button)(target));
            
            #line 107 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
            this.lastPage.Click += new System.Windows.RoutedEventHandler(this.LastPage_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.cmbJumData = ((System.Windows.Controls.ComboBox)(target));
            
            #line 114 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
            this.cmbJumData.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbJumData_SelectionChanged);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 7:
            
            #line 55 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Edit_Click);
            
            #line default
            #line hidden
            break;
            case 9:
            
            #line 66 "..\..\..\..\..\View\master\shift\shftMingguan.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Hapus_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

