#pragma checksum "..\..\..\..\..\View\master\employee\FormEmployee.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "C09038F45A09523F079BB77F324DD306C461096219615EFD4ADD0002BFCFBC38"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using rtwin.View.master.employee;


namespace rtwin.View.master.employee {
    
    
    /// <summary>
    /// FormEmployee
    /// </summary>
    public partial class FormEmployee : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox gbTitel;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer svGb;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtNip;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtPin;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtNama;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbKodeUnit;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbKodeDeputi;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmcmbKodeBiro;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbBagian;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbSubBagian;
        
        #line default
        #line hidden
        
        
        #line 63 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbJabatan;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbGolongan;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbGrade;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbEselon;
        
        #line default
        #line hidden
        
        
        #line 76 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbStatusPegawai;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker dpTmt;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker dpAktifHandPrint;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker dpTidakAktif;
        
        #line default
        #line hidden
        
        
        #line 88 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker dpTglLahir;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbGrupPolaJadwal;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtNoRekening;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtNpwp;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtNipBaru;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnsave;
        
        #line default
        #line hidden
        
        
        #line 106 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClose;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel lodongSave;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/rtwin;component/view/master/employee/formemployee.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.gbTitel = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 2:
            this.svGb = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 3:
            this.txtNip = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.txtPin = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.txtNama = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.cmbKodeUnit = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.cmbKodeDeputi = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 8:
            this.cmcmbKodeBiro = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 9:
            this.cmbBagian = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 10:
            this.cmbSubBagian = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 11:
            this.cmbJabatan = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 12:
            this.cmbGolongan = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 13:
            this.cmbGrade = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 14:
            this.cmbEselon = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 15:
            this.cmbStatusPegawai = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 16:
            this.dpTmt = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 17:
            this.dpAktifHandPrint = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 18:
            this.dpTidakAktif = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 19:
            this.dpTglLahir = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 20:
            this.cmbGrupPolaJadwal = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 21:
            this.txtNoRekening = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.txtNpwp = ((System.Windows.Controls.TextBox)(target));
            return;
            case 23:
            this.txtNipBaru = ((System.Windows.Controls.TextBox)(target));
            return;
            case 24:
            this.btnsave = ((System.Windows.Controls.Button)(target));
            
            #line 103 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
            this.btnsave.Click += new System.Windows.RoutedEventHandler(this.Btnsave_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.btnClose = ((System.Windows.Controls.Button)(target));
            
            #line 106 "..\..\..\..\..\View\master\employee\FormEmployee.xaml"
            this.btnClose.Click += new System.Windows.RoutedEventHandler(this.BtnClose_Click);
            
            #line default
            #line hidden
            return;
            case 26:
            this.lodongSave = ((System.Windows.Controls.StackPanel)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

