#pragma checksum "..\..\..\..\..\View\master\timecard\timecard_detail.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "5A4D8B32072E0A08F4C0D0A4823647DC66687706"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using rtwin.View.master.timecard;


namespace rtwin.View.master.timecard {
    
    
    /// <summary>
    /// timecard_detail
    /// </summary>
    public partial class timecard_detail : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 23 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddData;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSearch;
        
        #line default
        #line hidden
        
        
        #line 30 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.DialogHost dialog;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbKodeRange;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbSatker;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnTampilkan;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbSort;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSort;
        
        #line default
        #line hidden
        
        
        #line 69 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon arrowSort;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dgTimeCardDetail;
        
        #line default
        #line hidden
        
        
        #line 109 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button firstPage;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button prevPage;
        
        #line default
        #line hidden
        
        
        #line 118 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock dari;
        
        #line default
        #line hidden
        
        
        #line 121 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock sampai;
        
        #line default
        #line hidden
        
        
        #line 124 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock total;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button nextPage;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button lastPage;
        
        #line default
        #line hidden
        
        
        #line 139 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbJumData;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/rtwin;component/view/master/timecard/timecard_detail.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btnAddData = ((System.Windows.Controls.Button)(target));
            
            #line 23 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
            this.btnAddData.Click += new System.Windows.RoutedEventHandler(this.BtnAddData_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnSearch = ((System.Windows.Controls.Button)(target));
            
            #line 24 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
            this.btnSearch.Click += new System.Windows.RoutedEventHandler(this.BtnSearch_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.dialog = ((MaterialDesignThemes.Wpf.DialogHost)(target));
            return;
            case 4:
            this.cmbKodeRange = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            this.cmbSatker = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 6:
            this.btnTampilkan = ((System.Windows.Controls.Button)(target));
            
            #line 48 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
            this.btnTampilkan.Click += new System.Windows.RoutedEventHandler(this.BtnTampilkan_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.cmbSort = ((System.Windows.Controls.ComboBox)(target));
            
            #line 64 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
            this.cmbSort.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbSort_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.btnSort = ((System.Windows.Controls.Button)(target));
            
            #line 68 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
            this.btnSort.Click += new System.Windows.RoutedEventHandler(this.BtnSort_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.arrowSort = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 10:
            this.dgTimeCardDetail = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 13:
            this.firstPage = ((System.Windows.Controls.Button)(target));
            
            #line 109 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
            this.firstPage.Click += new System.Windows.RoutedEventHandler(this.FirstPage_Click);
            
            #line default
            #line hidden
            return;
            case 14:
            this.prevPage = ((System.Windows.Controls.Button)(target));
            
            #line 112 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
            this.prevPage.Click += new System.Windows.RoutedEventHandler(this.PrevPage_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            this.dari = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.sampai = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            this.total = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 18:
            this.nextPage = ((System.Windows.Controls.Button)(target));
            
            #line 129 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
            this.nextPage.Click += new System.Windows.RoutedEventHandler(this.NextPage_Click);
            
            #line default
            #line hidden
            return;
            case 19:
            this.lastPage = ((System.Windows.Controls.Button)(target));
            
            #line 132 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
            this.lastPage.Click += new System.Windows.RoutedEventHandler(this.LastPage_Click);
            
            #line default
            #line hidden
            return;
            case 20:
            this.cmbJumData = ((System.Windows.Controls.ComboBox)(target));
            
            #line 139 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
            this.cmbJumData.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbJumData_SelectionChanged);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 11:
            
            #line 80 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Edit_Click);
            
            #line default
            #line hidden
            break;
            case 12:
            
            #line 91 "..\..\..\..\..\View\master\timecard\timecard_detail.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Hapus_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

