#pragma checksum "..\..\..\..\..\View\master\satker\subBagian.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "28041F467CAC5E62DE8225B506A19BA3B9D67E1E54D9DD108C1F9AD0AF79248D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using rtwin.View.master.satker;


namespace rtwin.View.master.satker {
    
    
    /// <summary>
    /// subBagian
    /// </summary>
    public partial class subBagian : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 23 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnAddData;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSearch;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.DialogHost dialog;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbKodeDeputi;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbKodeBiro;
        
        #line default
        #line hidden
        
        
        #line 47 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbKodebagian;
        
        #line default
        #line hidden
        
        
        #line 54 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnTampilkan;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbSort;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnSort;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon arrowSort;
        
        #line default
        #line hidden
        
        
        #line 80 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid dgSubBagian;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn edit_header;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn hapus_header;
        
        #line default
        #line hidden
        
        
        #line 115 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button firstPage;
        
        #line default
        #line hidden
        
        
        #line 118 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button prevPage;
        
        #line default
        #line hidden
        
        
        #line 124 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock dari;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock sampai;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock total;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button nextPage;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button lastPage;
        
        #line default
        #line hidden
        
        
        #line 145 "..\..\..\..\..\View\master\satker\subBagian.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cmbJumData;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/rtwin;component/view/master/satker/subbagian.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.btnAddData = ((System.Windows.Controls.Button)(target));
            
            #line 23 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            this.btnAddData.Click += new System.Windows.RoutedEventHandler(this.BtnAddData_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.btnSearch = ((System.Windows.Controls.Button)(target));
            
            #line 26 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            this.btnSearch.Click += new System.Windows.RoutedEventHandler(this.BtnSearch_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.dialog = ((MaterialDesignThemes.Wpf.DialogHost)(target));
            return;
            case 4:
            this.cmbKodeDeputi = ((System.Windows.Controls.ComboBox)(target));
            
            #line 41 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            this.cmbKodeDeputi.DropDownClosed += new System.EventHandler(this.CmbKodeDeputi_DropDownClosed);
            
            #line default
            #line hidden
            return;
            case 5:
            this.cmbKodeBiro = ((System.Windows.Controls.ComboBox)(target));
            
            #line 44 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            this.cmbKodeBiro.DropDownClosed += new System.EventHandler(this.CmbKodeBiro_DropDownClosed);
            
            #line default
            #line hidden
            return;
            case 6:
            this.cmbKodebagian = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.btnTampilkan = ((System.Windows.Controls.Button)(target));
            
            #line 54 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            this.btnTampilkan.Click += new System.Windows.RoutedEventHandler(this.BtnTampilkan_Click);
            
            #line default
            #line hidden
            return;
            case 8:
            this.cmbSort = ((System.Windows.Controls.ComboBox)(target));
            
            #line 70 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            this.cmbSort.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbSort_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 9:
            this.btnSort = ((System.Windows.Controls.Button)(target));
            
            #line 74 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            this.btnSort.Click += new System.Windows.RoutedEventHandler(this.BtnSort_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.arrowSort = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 11:
            this.dgSubBagian = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 12:
            this.edit_header = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 14:
            this.hapus_header = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 16:
            this.firstPage = ((System.Windows.Controls.Button)(target));
            
            #line 115 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            this.firstPage.Click += new System.Windows.RoutedEventHandler(this.FirstPage_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.prevPage = ((System.Windows.Controls.Button)(target));
            
            #line 118 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            this.prevPage.Click += new System.Windows.RoutedEventHandler(this.PrevPage_Click);
            
            #line default
            #line hidden
            return;
            case 18:
            this.dari = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.sampai = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 20:
            this.total = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 21:
            this.nextPage = ((System.Windows.Controls.Button)(target));
            
            #line 135 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            this.nextPage.Click += new System.Windows.RoutedEventHandler(this.NextPage_Click);
            
            #line default
            #line hidden
            return;
            case 22:
            this.lastPage = ((System.Windows.Controls.Button)(target));
            
            #line 138 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            this.lastPage.Click += new System.Windows.RoutedEventHandler(this.LastPage_Click);
            
            #line default
            #line hidden
            return;
            case 23:
            this.cmbJumData = ((System.Windows.Controls.ComboBox)(target));
            
            #line 145 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            this.cmbJumData.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CmbJumData_SelectionChanged);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 13:
            
            #line 86 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Edit_Click);
            
            #line default
            #line hidden
            break;
            case 15:
            
            #line 97 "..\..\..\..\..\View\master\satker\subBagian.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Hapus_Click);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

