#pragma checksum "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8A4578C47BB19EF36A40B9C858B17F9028921B8B"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Xceed.Wpf.Toolkit;
using Xceed.Wpf.Toolkit.Chromes;
using Xceed.Wpf.Toolkit.Core.Converters;
using Xceed.Wpf.Toolkit.Core.Input;
using Xceed.Wpf.Toolkit.Core.Media;
using Xceed.Wpf.Toolkit.Core.Utilities;
using Xceed.Wpf.Toolkit.Obselete;
using Xceed.Wpf.Toolkit.Panels;
using Xceed.Wpf.Toolkit.Primitives;
using Xceed.Wpf.Toolkit.PropertyGrid;
using Xceed.Wpf.Toolkit.PropertyGrid.Attributes;
using Xceed.Wpf.Toolkit.PropertyGrid.Commands;
using Xceed.Wpf.Toolkit.PropertyGrid.Converters;
using Xceed.Wpf.Toolkit.PropertyGrid.Editors;
using Xceed.Wpf.Toolkit.Zoombox;
using rtwin.View.master.timecard;


namespace rtwin.View.master.timecard {
    
    
    /// <summary>
    /// FormEditDataTimeCard
    /// </summary>
    public partial class FormEditDataTimeCard : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 13 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.DialogHost dialogAlert;
        
        #line default
        #line hidden
        
        
        #line 16 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Frame contentAlert;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.GroupBox gbTitel;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel containerForm;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock exception;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox kodeRange;
        
        #line default
        #line hidden
        
        
        #line 52 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Xceed.Wpf.Toolkit.MaskedTextBox jamMasuk;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Xceed.Wpf.Toolkit.MaskedTextBox jamPulang;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Xceed.Wpf.Toolkit.MaskedTextBox tolTelat;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Xceed.Wpf.Toolkit.MaskedTextBox tolPulang;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Xceed.Wpf.Toolkit.MaskedTextBox limitAwal;
        
        #line default
        #line hidden
        
        
        #line 126 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Xceed.Wpf.Toolkit.MaskedTextBox limitAkhir;
        
        #line default
        #line hidden
        
        
        #line 140 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Xceed.Wpf.Toolkit.MaskedTextBox jamKerja;
        
        #line default
        #line hidden
        
        
        #line 155 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal Xceed.Wpf.Toolkit.MaskedTextBox jamIstirahat;
        
        #line default
        #line hidden
        
        
        #line 163 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnsave;
        
        #line default
        #line hidden
        
        
        #line 166 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClose;
        
        #line default
        #line hidden
        
        
        #line 169 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel lodongSave;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/rtwin;component/view/master/timecard/formeditdatatimecard.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.dialogAlert = ((MaterialDesignThemes.Wpf.DialogHost)(target));
            return;
            case 2:
            this.contentAlert = ((System.Windows.Controls.Frame)(target));
            return;
            case 3:
            this.gbTitel = ((System.Windows.Controls.GroupBox)(target));
            return;
            case 4:
            this.containerForm = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 5:
            this.exception = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.kodeRange = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.jamMasuk = ((Xceed.Wpf.Toolkit.MaskedTextBox)(target));
            return;
            case 8:
            this.jamPulang = ((Xceed.Wpf.Toolkit.MaskedTextBox)(target));
            return;
            case 9:
            this.tolTelat = ((Xceed.Wpf.Toolkit.MaskedTextBox)(target));
            return;
            case 10:
            this.tolPulang = ((Xceed.Wpf.Toolkit.MaskedTextBox)(target));
            return;
            case 11:
            this.limitAwal = ((Xceed.Wpf.Toolkit.MaskedTextBox)(target));
            return;
            case 12:
            this.limitAkhir = ((Xceed.Wpf.Toolkit.MaskedTextBox)(target));
            return;
            case 13:
            this.jamKerja = ((Xceed.Wpf.Toolkit.MaskedTextBox)(target));
            return;
            case 14:
            this.jamIstirahat = ((Xceed.Wpf.Toolkit.MaskedTextBox)(target));
            return;
            case 15:
            this.btnsave = ((System.Windows.Controls.Button)(target));
            
            #line 163 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
            this.btnsave.Click += new System.Windows.RoutedEventHandler(this.Btnsave_Click);
            
            #line default
            #line hidden
            return;
            case 16:
            this.btnClose = ((System.Windows.Controls.Button)(target));
            
            #line 166 "..\..\..\..\..\View\master\timecard\FormEditDataTimeCard.xaml"
            this.btnClose.Click += new System.Windows.RoutedEventHandler(this.BtnClose_Click);
            
            #line default
            #line hidden
            return;
            case 17:
            this.lodongSave = ((System.Windows.Controls.StackPanel)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

